name: post-pr

on:
  workflow_run:
    workflows: 
      - only-on-readme-change
    types:
      - completed
    
jobs:
  random:
    runs-on: ubuntu-latest
    steps:
      - name: random
        run: echo "random"
